### ISSUE TITLE
feature request: channel mover

### ISSUE THREAD

**Issue by bollowatsch** [roboalex2/csdc26bb-discord-bot#1]
Move messages to other textchannels, to get rid of other bots. similar to https://github.com/laralove143/interchannel_message_mover

**Comment by roboalex2** [comment]
Das feature wird nicht unterstützt von Discord. Der bot geht indem er einen Webhook erstellt mit dem selben namen und bild wie der User und diesen dann verwendet um die Nachricht neu in einem anderen Channel zu posten. Ist also relativ Aufwendig und der Nutzen ist klein, besonders da es schon einen Bot gibt. Wenn es aber wer implementieren möchte feel free.
